spring:
    main:
        show_banner: off
    application:
        name: com.simple.geocoding.app
    profiles:
        active: dev

---

spring.profiles: dev

---

spring.profiles: test

---

spring.profiles: prod
